### PR TITLE
Fixes #11: Install emulator package in `createEmulator`

### LINKED ISSUE #11: `createEmulator` fails if `emulator` package is missing
I deleted the cache directory and wanted to create a new emulator with a clean installation, which produced the following error:

```
    Error: Command failed with exit code 1: /path/to/avdmanager create avd --name android11 --package system-images;android-30;google_apis;x86_64 
    --device pixel_4
    Error: "emulator" package must be installed!
    null
    [=========                              ] 25% Loading local repository...       
    [=======================================] 100% Fetch remote repository...       
    Auto-selecting single ABI x86_64
```

andromatic should install the package in `createEmulator` if it is missing.

### PR DESCRIPTION
**Pull request by zner0L**

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -230,14 +230,16 @@ export type AvailablePackage = {
     description: string;
 };
 /**
- * Fetch a list of available packages that can be installed by `sdkmanager`.
+ * Fetch a list of available or installed packages that can be or have been installed by `sdkmanager`.
  *
+ * @param options If `ìnstalled` is true, fetch a list of all installed packages (instead of ones available for
+ *   install).
```
Comment (baltpeter) [inline src/index.ts]:
```suggestion
 *   install). Defaults to `false`.
```

File: src/emulator.ts [hunk 2]
```diff
@@ -94,6 +94,9 @@ export const createEmulator = async (name: string, options: EmulatorOptions) =>
     for (const dir of ['platforms', 'platform-tools'])
         if (!(await fs.pathExists(join(androidHome, dir)))) await fs.ensureDir(join(androidHome, dir));
 
+    // The `emulator` package is required by avdmanager, so we need to check for it
+    if (!(await isInstalled('emulator'))) await installPackages('emulator');
```
Comment (baltpeter) [inline src/emulator.ts]: While it doesn't take forever, the `sdkmanager` command here isn't particularly fast, either. I don't love having this overhead every time you create an emulator.

Any reason you're not just checking for the existence of the directory as we're doing in all other cases? I verified that `sdkmanager --list_installed` doesn't do anything more fancy, either.[^n]

[^n]: By that I mean it doesn't check whether an existing installation is corrupt or anything like that. It just checks for the presence of `$ANDROID_HOME/emulator/package.xml` (and parses that to show the version information, but we don't need that…).

The changes in `listPackages` are useful regardless.

**Review by baltpeter — APPROVED** [review]
